name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          cat metrics.txt >> report.md
          cml comment create report.md

          # Crear una tabla en Markdown con los resultados del modelo
          "| Métrica                | Valor          |" >> README1.md
          "|------------------------|----------------|" >> README1.md
          "| Test Accuracy          | ${test_accuracy} |" >> README1.md
          "| Best Parameters        | ${best_params}  |" >> README1.md
          "|------------------------|----------------|" >> README1.md
          
          # Agregar una descripción del modelo
          "" >> README.md
          "### Descripción de los Resultados del Modelo de Regresión Logística" >> README.md
          "Aquí se presentan los resultados obtenidos del modelo de regresión logística." >> README.md
          "La precisión en el conjunto de prueba y los mejores parámetros se detallan en la tabla anterior." >> README.md
